name: Build Lint Project
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run lint test
              run: run npm lint  
            - name: Run Test Code
              run: run npm test
            - name: Build code
              run: npm run build 
            - name: Deploy
              run: echo "Deploy shreyas's project"          