name: Build Pipeline
on: push
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v6
            - name: Install dependencies
              uses: npm ci
            - name: Build website
              uses: npm run build
            - name: Upload artifacts
              uses: actions/upload-artifact@v6
              with:
                name: Dist-files
                path: |
                    dist
                    package.json
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Deploy and testing"
                         